// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function MergeScores(arg1:string,arg2:string,arg3:Record<string, string>,arg4:number,arg5:number,arg6:number,arg7:number):Promise<dto.MergeResult>;

export function PreviewExcel(arg1:string):Promise<dto.ImportPreview>;

export function PreviewExcelBase64(arg1:string):Promise<dto.ImportPreview>;

export function PreviewExcelData(arg1:Array<number>):Promise<dto.ImportPreview>;

export function SaveExcelFile(arg1:string,arg2:string):Promise<string>;

export function SelectExcelFile():Promise<string>;
