// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MergeScores(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['wailsapp']['App']['MergeScores'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function PreviewExcel(arg1) {
  return window['go']['wailsapp']['App']['PreviewExcel'](arg1);
}

export function PreviewExcelBase64(arg1) {
  return window['go']['wailsapp']['App']['PreviewExcelBase64'](arg1);
}

export function PreviewExcelData(arg1) {
  return window['go']['wailsapp']['App']['PreviewExcelData'](arg1);
}

export function SaveExcelFile(arg1, arg2) {
  return window['go']['wailsapp']['App']['SaveExcelFile'](arg1, arg2);
}

export function SelectExcelFile() {
  return window['go']['wailsapp']['App']['SelectExcelFile']();
}
